# Generated by hand for seeding and systems update

from django.db import migrations

def update_and_seed_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    
    # 1. Update existing ingredients' compatible_systems
    # Citrus, berry, tropical, sour, artificial categories are not compatible with coffee by default
    soda_slushie_categories = ['citrus', 'berry', 'tropical', 'sour', 'artificial']
    all_systems_categories = ['herbal', 'sweet', 'spice']
    
    Ingredient.objects.filter(category__in=soda_slushie_categories).update(compatible_systems='SODA,SLUSHIE')
    Ingredient.objects.filter(category__in=all_systems_categories).update(compatible_systems='SODA,COFFEE,SLUSHIE')
    
    # 2. Seed default coffee bean ingredients
    coffee_beans = [
        ('Ethiopian Yirgacheffe', 'coffee', 3, 3, 4, 2, 4, 'Bright and floral with citrus notes', 'coffee, floral, citrus, bright'),
        ('Sumatra Mandheling', 'coffee', 4, 2, 2, 4, 3, 'Full-bodied, earthy, and herbal flavor profile', 'coffee, earthy, herbal, full-bodied'),
        ('Espresso Roast Blend', 'coffee', 5, 2, 2, 4, 3, 'Bold dark roast with chocolate and caramel notes', 'coffee, bold, chocolate, caramel')
    ]
    
    for name, category, intensity, sweetness, acidity, bitterness, complexity, description, flavor_notes in coffee_beans:
        Ingredient.objects.get_or_create(
            name=name,
            defaults={
                'ingredient_type': 'COFFEE_BEAN',
                'category': category,
                'intensity': intensity,
                'sweetness': sweetness,
                'acidity': acidity,
                'bitterness': bitterness,
                'complexity': complexity,
                'compatible_systems': 'COFFEE',
                'description': description,
                'flavor_notes': flavor_notes,
                'is_in_inventory': True
            }
        )

def reverse_update_and_seed(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(ingredient_type='COFFEE_BEAN').delete()
    Ingredient.objects.all().update(compatible_systems='SODA,COFFEE,SLUSHIE')


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0005_ingredient_complexity_and_more'),
    ]

    operations = [
        migrations.RunPython(update_and_seed_ingredients, reverse_update_and_seed),
    ]
