# Generated by Django 6.0.6 on 2026-06-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0006_seed_coffee_beans_and_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='enable_thinking',
            field=models.BooleanField(default=True, help_text='Enable internal model thinking/reasoning if supported by the provider/model.'),
        ),
    ]
