# Generated by Django 6.0.6 on 2026-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0007_llmprovider_enable_thinking'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='thinking_effort',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Thinking/reasoning effort level (low, medium, high) if supported by provider/model.', max_length=10),
        ),
    ]
