# Generated by Django 6.0.6 on 2026-06-15 20:09

import django.core.validators
from django.db import migrations, models


def backfill_suitability(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    CURATED_SUITABILITY = {
        'Lemon Lime': (4.5, 2.0),
        'Orange': (4.8, 1.5),
        'Grapefruit Pink': (4.2, 2.5),
        'Lime': (3.0, 4.0),
        'Blackberry': (4.0, 2.5),
        'Cranberry': (3.2, 3.8),
        'Wild Blueberry': (4.2, 2.0),
        'Strawberry': (4.5, 2.0),
        'Raspberry': (4.0, 3.0),
        'Mixed Berry': (4.6, 1.8),
        'Coconut': (3.2, 3.8),
        'Pineapple': (3.5, 3.5),
        'Mango': (4.0, 2.2),
        'Passion Fruit': (3.0, 4.2),
        'Cucumber': (2.5, 4.0),
        'Mint': (1.5, 4.8),
        'Vanilla': (2.0, 4.5),
        'Caramel Apple': (3.5, 3.5),
        'Green Apple': (4.0, 2.5),
        'Ethiopian Yirgacheffe': (4.8, 2.0),
        'Sumatra Mandheling': (4.8, 1.8),
        'Espresso Roast Blend': (5.0, 1.0),
    }
    
    for name, (base, accent) in CURATED_SUITABILITY.items():
        Ingredient.objects.filter(name=name).update(base_suitability=base, accent_suitability=accent)
        
    # Mark additives as accent-only
    Ingredient.objects.filter(ingredient_type='ADDITIVE').update(base_suitability=1.0, accent_suitability=4.0)


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0008_llmprovider_thinking_effort'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='accent_suitability',
            field=models.FloatField(default=3.0, help_text='AI-synthesized score representing how well this works as a supporting accent component (1.0 to 5.0)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='base_suitability',
            field=models.FloatField(default=3.0, help_text='AI-synthesized score representing how well this works as a dominant base component (1.0 to 5.0)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.RunPython(backfill_suitability, reverse_backfill),
    ]
