# Generated by Django 6.0.6 on 2026-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0009_ingredient_accent_suitability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='The manufacturer or brand of the syrup/reagent (e.g. Monin, Torani, Homemade)', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'brand')},
        ),
    ]
