# Generated by Django 6.0.6 on 2026-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0010_ingredient_brand_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ai_notes',
            field=models.TextField(blank=True, help_text='AI-generated notes about the flavor profile and pairings', null=True),
        ),
    ]
