# Generated by Django 6.0.3 on 2026-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0011_ingredient_ai_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='coffee_base_type',
            field=models.CharField(blank=True, choices=[('espresso', 'Espresso'), ('standard_brew', 'Standard Brew')], help_text='Whether the coffee base is espresso or a standard brew', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='coffee_style',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('iced', 'Iced'), ('espresso_shot', 'Espresso Shot')], help_text='Drink format: hot, iced, or espresso shot', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='drink_size_oz',
            field=models.FloatField(blank=True, help_text='Target drink size in oz (8/12/16/20 for drinks; 1/2 for espresso shots)', null=True),
        ),
    ]
