# Generated by Django 6.0.3 on 2026-06-18 20:49

from django.db import migrations, models

def migrate_dairy_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(
        models.Q(name__icontains='milk') | 
        models.Q(name__icontains='cream') | 
        models.Q(category='dairy')
    ).filter(ingredient_type='ADDITIVE').update(ingredient_type='DAIRY')

def reverse_migrate_dairy(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(ingredient_type='DAIRY').update(ingredient_type='ADDITIVE')

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0012_coffee_drink_format_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('SODA_SYRUP', 'Soda Syrup'), ('COFFEE_BEAN', 'Coffee Bean'), ('DAIRY', 'Dairy & Plant Milk'), ('ADDITIVE', 'Additive (Syrup, Sugar, Honey, etc.)'), ('OTHER', 'Other')], default='SODA_SYRUP', max_length=20),
        ),
        migrations.RunPython(migrate_dairy_ingredients, reverse_migrate_dairy),
    ]
