# Generated by Django 6.0.3 on 2026-06-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0013_alter_ingredient_ingredient_type'),
    ]

    operations = [
    ]
