# Generated by Django 6.0.3 on 2026-06-19 00:14

from django.db import migrations

def revert_heavy_cream_to_additive(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(name='Heavy Cream').update(ingredient_type='ADDITIVE')

def reverse_revert_heavy_cream(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(name='Heavy Cream').update(ingredient_type='DAIRY')

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0014_auto_20260618_2001'),
    ]

    operations = [
        migrations.RunPython(revert_heavy_cream_to_additive, reverse_revert_heavy_cream),
    ]
