# Generated by Django 6.0.3 on 2026-06-19 00:27

from django.db import migrations, models

def revert_creams_to_additive(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(
        models.Q(name__icontains='cream') | 
        models.Q(name__icontains='creamer')
    ).exclude(
        name__icontains='milk'
    ).update(ingredient_type='ADDITIVE')

def reverse_revert_creams(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(
        models.Q(name__icontains='cream') | 
        models.Q(name__icontains='creamer')
    ).exclude(
        name__icontains='milk'
    ).update(ingredient_type='DAIRY')

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0015_auto_20260618_2014'),
    ]

    operations = [
        migrations.RunPython(revert_creams_to_additive, reverse_revert_creams),
    ]
