# Generated by Django 5.0 on 2026-06-19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0016_revert_creams_to_additive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_ready_to_drink',
            field=models.BooleanField(
                default=False,
                help_text="Whether this ingredient is a ready-to-drink liquid (e.g. juices, milk, tea) that can serve as a primary volume filler."
            ),
        ),
    ]
