# Generated by Django 5.0 on 2026-06-19

from django.db import migrations

def set_dairy_to_ready_to_drink(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(ingredient_type='DAIRY').update(is_ready_to_drink=True)

def reverse_set_dairy(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(ingredient_type='DAIRY').update(is_ready_to_drink=False)

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0017_ingredient_is_ready_to_drink'),
    ]

    operations = [
        migrations.RunPython(set_dairy_to_ready_to_drink, reverse_set_dairy),
    ]
