# Generated by Django 6.0.6 on 2026-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0018_set_dairy_rtd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_dry',
            field=models.BooleanField(default=False, help_text='Whether this ingredient is measured in weight (g) rather than volume (ml/oz).'),
        ),
    ]
