# Generated by Django 6.0.6 on 2026-06-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0019_ingredient_is_dry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='acidity_score',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='bitterness_score',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='body_intensity',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_decaf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='flavor_notes',
            field=models.TextField(blank=True, help_text="Comma-separated flavor descriptors (e.g., 'berry, chocolatey, floral')"),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('DARK', 'Dark')], default='MEDIUM', max_length=10, null=True),
        ),
    ]
