# Generated by Django 6.0.6 on 2026-06-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0020_ingredient_acidity_score_ingredient_bitterness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Designates this ingredient as the primary flavor anchor for Soda synthesis.'),
        ),
    ]
