# Generated by hand for updating Coconut Water configuration

from django.db import migrations

def update_coconut_water(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(name='Coconut Water').update(
        description="Hydrating base compound with a baseline natural sugar density of 3% by volume weight."
    )

def reverse_update(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    Ingredient.objects.filter(name='Coconut Water').update(
        description=""
    )

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0021_recipeingredient_is_primary'),
    ]

    operations = [
        migrations.RunPython(update_coconut_water, reverse_update),
    ]
