# Generated by Django 6.0.6 on 2026-06-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0022_update_coconut_water_sugar_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='enable_keep_warm',
            field=models.BooleanField(default=False, help_text='Enable background periodic keep-alive tasks to maintain model in VRAM.'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='enable_thinking',
            field=models.BooleanField(default=False, help_text='Enable internal model thinking/reasoning if supported by the provider/model.'),
        ),
    ]
