# Generated by Django 6.0.6 on 2026-06-30 04:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0025_ingredient_deleted_at_ingredient_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundExecutionTask',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
