# Generated by Django 6.0.6 on 2026-07-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0026_backgroundexecutiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='favorite',
            field=models.BooleanField(default=False, help_text='Whether this ingredient is a favorite/preferred reagent.'),
        ),
    ]
