# Generated by Django 6.0.7 on 2026-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0027_ingredient_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='mixology_function',
            field=models.CharField(choices=[('VOLUME_BASE', 'Volume Base'), ('FLAVORING', 'Flavoring'), ('SWEETENER', 'Sweetener'), ('TEXTURIZER', 'Texturizer'), ('GARNISH', 'Garnish')], db_index=True, default='FLAVORING', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='physical_state',
            field=models.CharField(choices=[('LIQUID', 'Liquid'), ('SYRUP', 'Syrup'), ('SAUCE', 'Sauce'), ('POWDER', 'Powder'), ('SOLID_EXTRACTABLE', 'Solid Extractable')], db_index=True, default='SYRUP', max_length=20),
        ),
    ]
