# Generated by Django 6.0.7 on 2026-07-17 19:25

from django.db import migrations

def migrate_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('flavors', 'Ingredient')
    for ing in Ingredient.objects.all():
        name_lower = ing.name.lower()
        
        # Default fallback values
        p_state = 'SYRUP'
        m_func = 'FLAVORING'
        
        if ing.ingredient_type == 'COFFEE_BEAN':
            p_state = 'SOLID_EXTRACTABLE'
            m_func = 'FLAVORING'
        elif ing.ingredient_type == 'DAIRY':
            if 'cream' in name_lower or 'half' in name_lower or 'whipped' in name_lower:
                p_state = 'SAUCE'
                m_func = 'TEXTURIZER'
            else:
                p_state = 'LIQUID'
                m_func = 'VOLUME_BASE'
        elif ing.is_ready_to_drink:
            p_state = 'LIQUID'
            m_func = 'VOLUME_BASE'
        elif ing.is_dry:
            p_state = 'POWDER'
            if any(x in name_lower for x in ['sugar', 'sweetener', 'stevia', 'splenda', 'honey powder', 'erythritol']):
                m_func = 'SWEETENER'
            elif any(x in name_lower for x in ['cinnamon', 'nutmeg', 'dust', 'powder', 'cocoa', 'matcha']):
                m_func = 'GARNISH'
            else:
                m_func = 'FLAVORING'
        else:
            # Check by names for ADDITIVE and OTHER
            if any(x in name_lower for x in ['honey', 'agave', 'maple', 'caramel', 'chocolate', 'fudge', 'sauce', 'puree']):
                p_state = 'SAUCE'
                if any(x in name_lower for x in ['honey', 'agave', 'maple']):
                    m_func = 'SWEETENER'
                else:
                    m_func = 'FLAVORING'
            elif any(x in name_lower for x in ['sugar', 'simple syrup', 'syrup sugar']):
                p_state = 'SYRUP'
                m_func = 'SWEETENER'
            elif any(x in name_lower for x in ['syrup', 'monin', 'torani', 'extract', 'bitters']):
                p_state = 'SYRUP'
                m_func = 'FLAVORING'
            elif any(x in name_lower for x in ['water', 'juice', 'club soda', 'soda water', 'tonic']):
                p_state = 'LIQUID'
                m_func = 'VOLUME_BASE'
            else:
                p_state = 'SYRUP'
                m_func = 'FLAVORING'
                
        ing.physical_state = p_state
        ing.mixology_function = m_func
        ing.save()

def reverse_migrate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0028_ingredient_mixology_function_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_ingredients, reverse_migrate),
    ]

