# Generated by Django 6.0.7 on 2026-07-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0029_migrate_ingredient_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_type',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='is_dry',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='is_ready_to_drink',
        ),
    ]
