# Generated by Django 6.0.8 on 2026-08-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0030_remove_ingredient_ingredient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixhistory',
            name='drink_type',
            field=models.CharField(choices=[('SODA', 'Soda Synthesis'), ('COFFEE', 'Coffee Laboratory'), ('CRYO', 'Cryo-Slushie Lab')], default='SODA', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='drink_type',
            field=models.CharField(choices=[('SODA', 'Soda Synthesis'), ('COFFEE', 'Coffee Laboratory'), ('CRYO', 'Cryo-Slushie Lab')], default='SODA', max_length=10),
        ),
    ]
