# Generated by Django 6.0.8 on 2026-08-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0031_alter_mixhistory_drink_type_alter_recipe_drink_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=1.0, help_text='Amount (relative parts out of 100)'),
        ),
    ]
