# Generated by Django 6.0.8 on 2026-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0032_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(default=1.0, help_text='Amount (relative parts)'),
        ),
    ]
