# Generated by Django 6.0.8 on 2026-09-20 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0033_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='sugar_content_brix',
            field=models.FloatField(blank=True, help_text='Physical sugar content percentage (e.g., 65.0 for 65% Brix). Leave blank to use engine default approximations.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
