# Generated by Django 6.0.8 on 2026-09-20 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavors', '0034_ingredient_sugar_content_brix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='sugar_content_brix',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar_grams_per_30ml',
            field=models.FloatField(blank=True, help_text='Grams of sugar per 1oz (30ml) serving. Leave blank to use engine default approximations.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)]),
        ),
    ]
